FROM dlibubuntu as builder
RUN apt-get install wget git gcc g++ -y

RUN wget https://dl.google.com/go/go1.13.8.linux-amd64.tar.gz
RUN tar -xf go1.13.8.linux-amd64.tar.gz
RUN mv go /usr/local

ENV GOROOT /usr/local/go
ENV GOPATH /go
ENV PATH $GOPATH/bin:$GOROOT/bin:$PATH
RUN mkdir $GOPATH
RUN go get -v github.com/Kagami/go-face 

